name: stage_assistant
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  beamer: ^1.6.1
  collection: ^1.18.0
  crdt: ^5.1.2
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_rust_bridge: ^1.82.6
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  go_router: ^14.1.0
  hlc: ^1.0.4
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  js: ^0.6.7
  logger: ^2.3.0
  logging: ^1.2.0
  mqtt_client: ^10.2.1
  pdfrx: ^1.0.63
  pdfx:
      git:
        url: 'https://github.com/ScerIO/packages.flutter'
        ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'
        path: packages/pdfx
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  web_socket_channel: ^2.4.5
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/input.pdf
