# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\":\n\x10\x41\x64\x64MarginRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0bmargin_side\x18\x02 \x01(\t\"&\n\x11\x41\x64\x64MarginResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x1f\n\nOCRRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\" \n\x0bOCRResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x0e\n\x0cStartRequest\" \n\rStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\r\n\x0bStopRequest\"\x1f\n\x0cStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0f\n\rStatusRequest\"e\n\x0eStatusResponse\x12\x12\n\nrpc_status\x18\x01 \x01(\t\x12\x1d\n\x15speech_to_line_status\x18\x02 \x01(\t\x12 \n\x18performer_tracker_status\x18\x03 \x01(\t2\xee\x02\n\rScriptService\x12\x32\n\tAddMargin\x12\x11.AddMarginRequest\x1a\x12.AddMarginResponse\x12\'\n\nPerformOCR\x12\x0b.OCRRequest\x1a\x0c.OCRResponse\x12\x32\n\x11StartSpeechToLine\x12\r.StartRequest\x1a\x0e.StartResponse\x12/\n\x10StopSpeechToLine\x12\x0c.StopRequest\x1a\r.StopResponse\x12\x36\n\x15StartPerformerTracker\x12\r.StartRequest\x1a\x0e.StartResponse\x12\x33\n\x14StopPerformerTracker\x12\x0c.StopRequest\x1a\r.StopResponse\x12.\n\x0bGetStatuses\x12\x0e.StatusRequest\x1a\x0f.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDMARGINREQUEST']._serialized_start=17
  _globals['_ADDMARGINREQUEST']._serialized_end=75
  _globals['_ADDMARGINRESPONSE']._serialized_start=77
  _globals['_ADDMARGINRESPONSE']._serialized_end=115
  _globals['_OCRREQUEST']._serialized_start=117
  _globals['_OCRREQUEST']._serialized_end=148
  _globals['_OCRRESPONSE']._serialized_start=150
  _globals['_OCRRESPONSE']._serialized_end=182
  _globals['_STARTREQUEST']._serialized_start=184
  _globals['_STARTREQUEST']._serialized_end=198
  _globals['_STARTRESPONSE']._serialized_start=200
  _globals['_STARTRESPONSE']._serialized_end=232
  _globals['_STOPREQUEST']._serialized_start=234
  _globals['_STOPREQUEST']._serialized_end=247
  _globals['_STOPRESPONSE']._serialized_start=249
  _globals['_STOPRESPONSE']._serialized_end=280
  _globals['_STATUSREQUEST']._serialized_start=282
  _globals['_STATUSREQUEST']._serialized_end=297
  _globals['_STATUSRESPONSE']._serialized_start=299
  _globals['_STATUSRESPONSE']._serialized_end=400
  _globals['_SCRIPTSERVICE']._serialized_start=403
  _globals['_SCRIPTSERVICE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
