# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\":\n\x10\x41\x64\x64MarginRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0bmargin_side\x18\x02 \x01(\t\"&\n\x11\x41\x64\x64MarginResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x1f\n\nOCRRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x1b\n\x0bOCRResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2l\n\rScriptService\x12\x32\n\tAddMargin\x12\x11.AddMarginRequest\x1a\x12.AddMarginResponse\x12\'\n\nPerformOCR\x12\x0b.OCRRequest\x1a\x0c.OCRResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDMARGINREQUEST']._serialized_start=17
  _globals['_ADDMARGINREQUEST']._serialized_end=75
  _globals['_ADDMARGINRESPONSE']._serialized_start=77
  _globals['_ADDMARGINRESPONSE']._serialized_end=115
  _globals['_OCRREQUEST']._serialized_start=117
  _globals['_OCRREQUEST']._serialized_end=148
  _globals['_OCRRESPONSE']._serialized_start=150
  _globals['_OCRRESPONSE']._serialized_end=177
  _globals['_SCRIPTSERVICE']._serialized_start=179
  _globals['_SCRIPTSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
